export const PHYSICS = {
    GRAVITY: 300,
    THRUST_POWER: 400,
    LATERAL_THRUST_POWER: 300,
    DOWNWARD_THRUST_POWER: 200,
    MAX_VELOCITY: 500,
    DRAG: 0.98,
    BOUNCE: 0.3,
    EMERGENCY_BRAKE_POWER: 0.1,
} as const;
